# Generated by Django 5.2.2 on 2025-06-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
