# Generated by Django 5.2.2 on 2025-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
